import subprocess
import sys
from pathlib import Path
from tempfile import TemporaryDirectory
import unittest


ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "backend"))

import app as app_module
from app import app
from domain.logic_graph import build_logic_graph, validate_logic_graph
from domain.migrations import migrate_project
from domain.seed import demo_project


class LogicGraphTest(unittest.TestCase):
    def test_graph_has_typed_nodes_and_evidence_edges(self):
        graph = build_logic_graph(migrate_project(demo_project()))
        self.assertEqual(validate_logic_graph(graph), [])
        node_kinds = {item["kind"] for item in graph["nodes"]}
        edge_kinds = {item["kind"] for item in graph["edges"]}

        self.assertTrue({"proposition", "differential-claim", "differential-event", "class-fate", "period-family", "grading-sector", "c3-action"}.issubset(node_kinds))
        self.assertTrue({"asserts", "updates", "certifies", "belongs-to", "tracks-orbit"}.issubset(edge_kinds))
        self.assertEqual(len(graph["nodes"]), len({item["id"] for item in graph["nodes"]}))

    def test_differential_proposition_asserts_its_claim(self):
        graph = build_logic_graph(migrate_project(demo_project()))
        self.assertIn(
            {
                "source": "proposition:prop_two_d3_u",
                "target": "differential:diff_two_d3_u",
                "kind": "asserts",
            },
            graph["edges"],
        )


class V2ApiAndUiTest(unittest.TestCase):
    def setUp(self):
        self.client = app.test_client()
        self.data_dir = TemporaryDirectory()
        self.old_data_path = app_module.DATA_PATH
        app_module.DATA_PATH = Path(self.data_dir.name) / "project.json"

    def tearDown(self):
        app_module.DATA_PATH = self.old_data_path
        self.data_dir.cleanup()

    def test_v2_graph_fate_and_period_endpoints(self):
        graph = self.client.get("/api/v2/logic-graph")
        self.assertEqual(graph.status_code, 200)
        self.assertTrue(graph.get_json()["nodes"])
        periods = self.client.get("/api/v2/period-families")
        self.assertEqual(periods.status_code, 200)
        self.assertTrue(periods.get_json()["period_families"])
        fates = self.client.get("/api/v2/workspaces/ws_2sigma_i/fates")
        self.assertEqual(fates.status_code, 200)
        self.assertTrue(fates.get_json()["events"])

    def test_tex_exports_are_deterministic_and_keep_review_statuses(self):
        chart = self.client.get("/api/v2/render/workspaces/ws_3sigma_i/chart.tex?page=9")
        self.assertEqual(chart.status_code, 200)
        self.assertEqual(chart.mimetype, "application/x-tex")
        self.assertIn(b"Generated by HFPSS Studio", chart.data)
        self.assertIn(b"review differential", chart.data)
        self.assertIn(b'"proposition_id"', chart.data)
        self.assertIn(b"custom_tikz_template=", chart.data)
        self.assertIn(b"d9/.style", chart.data)
        self.assertNotIn(b"spectralsequences", chart.data)

        article = self.client.get("/api/v2/render/workspaces/ws_3sigma_i/article.tex?page=9")
        self.assertEqual(article.status_code, 200)
        self.assertIn(b"Differential register", article.data)
        self.assertIn(b"under-review", article.data)
        self.assertIn(b"Proof appendix", article.data)

        invalid = self.client.get("/api/v2/render/workspaces/ws_3sigma_i/unknown.tex")
        self.assertEqual(invalid.status_code, 404)

    def test_frontend_exposes_atlas_fate_graph_and_product_workflows(self):
        markup = (ROOT / "backend" / "templates" / "index.html").read_text(encoding="utf-8")
        script = (ROOT / "backend" / "static" / "app.js").read_text(encoding="utf-8")

        for ident in ("grading-atlas", "fate-inspector", "logic-graph", "product-form", "product-preview"):
            self.assertIn(f'id="{ident}"', markup)
        self.assertIn("first_hfpss_death", script)
        self.assertIn("tate_only_negative_source", script)
        self.assertIn("function renderGradingAtlas", script)
        self.assertIn("function renderFateInspector", script)
        self.assertIn("function renderLogicGraph", script)
        self.assertIn("/api/v2/products/preview", script)
        self.assertIn("usablePeriodFamily", script)
        self.assertNotIn(".filter((item) => item.page < page)\n      .flatMap", script)
        self.assertIn("proof history retained", script)
        self.assertIn('id="export-chart"', markup)
        self.assertIn('id="export-article"', markup)
        self.assertIn("function downloadTex", script)

    def test_javascript_is_syntactically_valid_when_node_is_available(self):
        try:
            completed = subprocess.run(
                ["node", "--check", str(ROOT / "backend" / "static" / "app.js")],
                capture_output=True,
                text=True,
                timeout=20,
            )
        except FileNotFoundError:
            self.skipTest("Node.js is not installed in this environment.")
        self.assertEqual(completed.returncode, 0, completed.stderr)


if __name__ == "__main__":
    unittest.main()
